// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bilibili-lite/internal/biz"
	"bilibili-lite/internal/conf"
	"bilibili-lite/internal/data"
	"bilibili-lite/internal/media"
	"bilibili-lite/internal/middleware"
	"bilibili-lite/internal/server"
	"bilibili-lite/internal/service"
	"bilibili-lite/internal/worker"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp assembles the application and its cleanup function.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger *slog.Logger) (*kratos.App, func(), error) {
	tokenManager, err := middleware.NewJWTManager(auth)
	if err != nil {
		return nil, nil, err
	}
	authenticator := middleware.NewAuthenticator(tokenManager)
	dataData, cleanup, err := data.NewData(confData)
	if err != nil {
		return nil, nil, err
	}
	manager, err := media.NewManager(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	videoRepo := data.NewVideoRepo(dataData, manager)
	videoUsecase := biz.NewVideoUsecase(videoRepo)
	videoService := service.NewVideoService(videoUsecase)
	userRepo := data.NewUserRepo(dataData)
	userUsecase := biz.NewUserUsecase(userRepo, tokenManager)
	userService := service.NewUserService(userUsecase, manager)
	grpcServer := server.NewGRPCServer(confServer, authenticator, videoService, userService)
	videoUploadHTTPHandler := service.NewVideoUploadHTTPHandler(videoUsecase, confData)
	httpServer := server.NewHTTPServer(confServer, confData, manager, authenticator, videoService, videoUploadHTTPHandler, userService)
	uploadJanitor := worker.NewUploadJanitor(manager)
	app := newApp(logger, grpcServer, httpServer, uploadJanitor)
	return app, func() {
		cleanup()
	}, nil
}
