// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: video/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_VIDEO_UNSPECIFIED        ErrorReason = 0
	ErrorReason_VIDEO_NOT_FOUND          ErrorReason = 1
	ErrorReason_VIDEO_INVALID_ARGUMENT   ErrorReason = 2
	ErrorReason_VIDEO_PROCESSING_FAILED  ErrorReason = 3
	ErrorReason_VIDEO_UPLOAD_INTERRUPTED ErrorReason = 4
	ErrorReason_VIDEO_UPLOAD_TOO_LARGE   ErrorReason = 5
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "VIDEO_UNSPECIFIED",
		1: "VIDEO_NOT_FOUND",
		2: "VIDEO_INVALID_ARGUMENT",
		3: "VIDEO_PROCESSING_FAILED",
		4: "VIDEO_UPLOAD_INTERRUPTED",
		5: "VIDEO_UPLOAD_TOO_LARGE",
	}
	ErrorReason_value = map[string]int32{
		"VIDEO_UNSPECIFIED":        0,
		"VIDEO_NOT_FOUND":          1,
		"VIDEO_INVALID_ARGUMENT":   2,
		"VIDEO_PROCESSING_FAILED":  3,
		"VIDEO_UPLOAD_INTERRUPTED": 4,
		"VIDEO_UPLOAD_TOO_LARGE":   5,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_video_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_video_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_video_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_video_v1_error_reason_proto protoreflect.FileDescriptor

const file_video_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1bvideo/v1/error_reason.proto\x12\bvideo.v1*\xac\x01\n" +
	"\vErrorReason\x12\x15\n" +
	"\x11VIDEO_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fVIDEO_NOT_FOUND\x10\x01\x12\x1a\n" +
	"\x16VIDEO_INVALID_ARGUMENT\x10\x02\x12\x1b\n" +
	"\x17VIDEO_PROCESSING_FAILED\x10\x03\x12\x1c\n" +
	"\x18VIDEO_UPLOAD_INTERRUPTED\x10\x04\x12\x1a\n" +
	"\x16VIDEO_UPLOAD_TOO_LARGE\x10\x05B8\n" +
	"\bvideo.v1P\x01Z\x1dbilibili-lite/api/video/v1;v1\xa2\x02\n" +
	"APIVideoV1b\x06proto3"

var (
	file_video_v1_error_reason_proto_rawDescOnce sync.Once
	file_video_v1_error_reason_proto_rawDescData []byte
)

func file_video_v1_error_reason_proto_rawDescGZIP() []byte {
	file_video_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_video_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_v1_error_reason_proto_rawDesc), len(file_video_v1_error_reason_proto_rawDesc)))
	})
	return file_video_v1_error_reason_proto_rawDescData
}

var file_video_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_video_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: video.v1.ErrorReason
}
var file_video_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_video_v1_error_reason_proto_init() }
func file_video_v1_error_reason_proto_init() {
	if File_video_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_v1_error_reason_proto_rawDesc), len(file_video_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_video_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_video_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_video_v1_error_reason_proto_enumTypes,
	}.Build()
	File_video_v1_error_reason_proto = out.File
	file_video_v1_error_reason_proto_goTypes = nil
	file_video_v1_error_reason_proto_depIdxs = nil
}
