// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: video/v1/video.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Video struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Bvid            string                 `protobuf:"bytes,1,opt,name=bvid,proto3" json:"bvid,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerName       string                 `protobuf:"bytes,4,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerAvatarUrl  string                 `protobuf:"bytes,5,opt,name=owner_avatar_url,json=ownerAvatarUrl,proto3" json:"owner_avatar_url,omitempty"`
	CoverUrl        string                 `protobuf:"bytes,6,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	DurationSeconds int64                  `protobuf:"varint,7,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	ViewCount       int64                  `protobuf:"varint,8,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	DanmakuCount    int64                  `protobuf:"varint,9,opt,name=danmaku_count,json=danmakuCount,proto3" json:"danmaku_count,omitempty"`
	LikeCount       int64                  `protobuf:"varint,10,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CoinCount       int64                  `protobuf:"varint,11,opt,name=coin_count,json=coinCount,proto3" json:"coin_count,omitempty"`
	FavoriteCount   int64                  `protobuf:"varint,12,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`
	ShareCount      int64                  `protobuf:"varint,13,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	PublishTime     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	Tags            []string               `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_video_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *Video) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Video) GetOwnerAvatarUrl() string {
	if x != nil {
		return x.OwnerAvatarUrl
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Video) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Video) GetDanmakuCount() int64 {
	if x != nil {
		return x.DanmakuCount
	}
	return 0
}

func (x *Video) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Video) GetCoinCount() int64 {
	if x != nil {
		return x.CoinCount
	}
	return 0
}

func (x *Video) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Video) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *Video) GetPublishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishTime
	}
	return nil
}

func (x *Video) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type VideoPlay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvid          string                 `protobuf:"bytes,1,opt,name=bvid,proto3" json:"bvid,omitempty"`
	Streams       []*VideoStream         `protobuf:"bytes,2,rep,name=streams,proto3" json:"streams,omitempty"`
	Danmaku       *DanmakuConfig         `protobuf:"bytes,3,opt,name=danmaku,proto3" json:"danmaku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoPlay) Reset() {
	*x = VideoPlay{}
	mi := &file_video_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoPlay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoPlay) ProtoMessage() {}

func (x *VideoPlay) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoPlay.ProtoReflect.Descriptor instead.
func (*VideoPlay) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *VideoPlay) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

func (x *VideoPlay) GetStreams() []*VideoStream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *VideoPlay) GetDanmaku() *DanmakuConfig {
	if x != nil {
		return x.Danmaku
	}
	return nil
}

type VideoStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Codec         string                 `protobuf:"bytes,3,opt,name=codec,proto3" json:"codec,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Bandwidth     int32                  `protobuf:"varint,8,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	DefaultStream bool                   `protobuf:"varint,9,opt,name=default_stream,json=defaultStream,proto3" json:"default_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoStream) Reset() {
	*x = VideoStream{}
	mi := &file_video_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoStream) ProtoMessage() {}

func (x *VideoStream) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoStream.ProtoReflect.Descriptor instead.
func (*VideoStream) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{2}
}

func (x *VideoStream) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoStream) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *VideoStream) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *VideoStream) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *VideoStream) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VideoStream) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoStream) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoStream) GetBandwidth() int32 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *VideoStream) GetDefaultStream() bool {
	if x != nil {
		return x.DefaultStream
	}
	return false
}

type DanmakuConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Items         []*DanmakuItem         `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuConfig) Reset() {
	*x = DanmakuConfig{}
	mi := &file_video_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuConfig) ProtoMessage() {}

func (x *DanmakuConfig) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuConfig.ProtoReflect.Descriptor instead.
func (*DanmakuConfig) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{3}
}

func (x *DanmakuConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DanmakuConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DanmakuConfig) GetItems() []*DanmakuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DanmakuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeSeconds   float64                `protobuf:"fixed64,1,opt,name=time_seconds,json=timeSeconds,proto3" json:"time_seconds,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DanmakuItem) Reset() {
	*x = DanmakuItem{}
	mi := &file_video_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DanmakuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DanmakuItem) ProtoMessage() {}

func (x *DanmakuItem) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DanmakuItem.ProtoReflect.Descriptor instead.
func (*DanmakuItem) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *DanmakuItem) GetTimeSeconds() float64 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *DanmakuItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *DanmakuItem) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvid          string                 `protobuf:"bytes,1,opt,name=bvid,proto3" json:"bvid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_video_v1_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{5}
}

func (x *GetVideoRequest) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

type GetVideoPlayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvid          string                 `protobuf:"bytes,1,opt,name=bvid,proto3" json:"bvid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoPlayRequest) Reset() {
	*x = GetVideoPlayRequest{}
	mi := &file_video_v1_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoPlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoPlayRequest) ProtoMessage() {}

func (x *GetVideoPlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoPlayRequest.ProtoReflect.Descriptor instead.
func (*GetVideoPlayRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{6}
}

func (x *GetVideoPlayRequest) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

type GetVideoLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvid          string                 `protobuf:"bytes,1,opt,name=bvid,proto3" json:"bvid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoLikeRequest) Reset() {
	*x = GetVideoLikeRequest{}
	mi := &file_video_v1_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoLikeRequest) ProtoMessage() {}

func (x *GetVideoLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoLikeRequest.ProtoReflect.Descriptor instead.
func (*GetVideoLikeRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideoLikeRequest) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

type LikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvid          string                 `protobuf:"bytes,1,opt,name=bvid,proto3" json:"bvid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoRequest) Reset() {
	*x = LikeVideoRequest{}
	mi := &file_video_v1_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoRequest) ProtoMessage() {}

func (x *LikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoRequest.ProtoReflect.Descriptor instead.
func (*LikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{8}
}

func (x *LikeVideoRequest) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

type UnlikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvid          string                 `protobuf:"bytes,1,opt,name=bvid,proto3" json:"bvid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeVideoRequest) Reset() {
	*x = UnlikeVideoRequest{}
	mi := &file_video_v1_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeVideoRequest) ProtoMessage() {}

func (x *UnlikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeVideoRequest.ProtoReflect.Descriptor instead.
func (*UnlikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{9}
}

func (x *UnlikeVideoRequest) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

type VideoLike struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bvid          string                 `protobuf:"bytes,1,opt,name=bvid,proto3" json:"bvid,omitempty"`
	Liked         bool                   `protobuf:"varint,2,opt,name=liked,proto3" json:"liked,omitempty"`
	LikeCount     int64                  `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoLike) Reset() {
	*x = VideoLike{}
	mi := &file_video_v1_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoLike) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoLike) ProtoMessage() {}

func (x *VideoLike) ProtoReflect() protoreflect.Message {
	mi := &file_video_v1_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoLike.ProtoReflect.Descriptor instead.
func (*VideoLike) Descriptor() ([]byte, []int) {
	return file_video_v1_video_proto_rawDescGZIP(), []int{10}
}

func (x *VideoLike) GetBvid() string {
	if x != nil {
		return x.Bvid
	}
	return ""
}

func (x *VideoLike) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

func (x *VideoLike) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

var File_video_v1_video_proto protoreflect.FileDescriptor

const file_video_v1_video_proto_rawDesc = "" +
	"\n" +
	"\x14video/v1/video.proto\x12\bvideo.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x04\n" +
	"\x05Video\x12\x12\n" +
	"\x04bvid\x18\x01 \x01(\tR\x04bvid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x04 \x01(\tR\townerName\x12(\n" +
	"\x10owner_avatar_url\x18\x05 \x01(\tR\x0eownerAvatarUrl\x12\x1b\n" +
	"\tcover_url\x18\x06 \x01(\tR\bcoverUrl\x12)\n" +
	"\x10duration_seconds\x18\a \x01(\x03R\x0fdurationSeconds\x12\x1d\n" +
	"\n" +
	"view_count\x18\b \x01(\x03R\tviewCount\x12#\n" +
	"\rdanmaku_count\x18\t \x01(\x03R\fdanmakuCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\n" +
	" \x01(\x03R\tlikeCount\x12\x1d\n" +
	"\n" +
	"coin_count\x18\v \x01(\x03R\tcoinCount\x12%\n" +
	"\x0efavorite_count\x18\f \x01(\x03R\rfavoriteCount\x12\x1f\n" +
	"\vshare_count\x18\r \x01(\x03R\n" +
	"shareCount\x12=\n" +
	"\fpublish_time\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vpublishTime\x12\x12\n" +
	"\x04tags\x18\x0f \x03(\tR\x04tags\"\x83\x01\n" +
	"\tVideoPlay\x12\x12\n" +
	"\x04bvid\x18\x01 \x01(\tR\x04bvid\x12/\n" +
	"\astreams\x18\x02 \x03(\v2\x15.video.v1.VideoStreamR\astreams\x121\n" +
	"\adanmaku\x18\x03 \x01(\v2\x17.video.v1.DanmakuConfigR\adanmaku\"\xeb\x01\n" +
	"\vVideoStream\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05codec\x18\x03 \x01(\tR\x05codec\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x05R\x06height\x12\x1c\n" +
	"\tbandwidth\x18\b \x01(\x05R\tbandwidth\x12%\n" +
	"\x0edefault_stream\x18\t \x01(\bR\rdefaultStream\"n\n" +
	"\rDanmakuConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12+\n" +
	"\x05items\x18\x03 \x03(\v2\x15.video.v1.DanmakuItemR\x05items\"Z\n" +
	"\vDanmakuItem\x12!\n" +
	"\ftime_seconds\x18\x01 \x01(\x01R\vtimeSeconds\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"*\n" +
	"\x0fGetVideoRequest\x12\x17\n" +
	"\x04bvid\x18\x01 \x01(\tB\x03\xe0A\x02R\x04bvid\".\n" +
	"\x13GetVideoPlayRequest\x12\x17\n" +
	"\x04bvid\x18\x01 \x01(\tB\x03\xe0A\x02R\x04bvid\".\n" +
	"\x13GetVideoLikeRequest\x12\x17\n" +
	"\x04bvid\x18\x01 \x01(\tB\x03\xe0A\x02R\x04bvid\"+\n" +
	"\x10LikeVideoRequest\x12\x17\n" +
	"\x04bvid\x18\x01 \x01(\tB\x03\xe0A\x02R\x04bvid\"-\n" +
	"\x12UnlikeVideoRequest\x12\x17\n" +
	"\x04bvid\x18\x01 \x01(\tB\x03\xe0A\x02R\x04bvid\"T\n" +
	"\tVideoLike\x12\x12\n" +
	"\x04bvid\x18\x01 \x01(\tR\x04bvid\x12\x14\n" +
	"\x05liked\x18\x02 \x01(\bR\x05liked\x12\x1d\n" +
	"\n" +
	"like_count\x18\x03 \x01(\x03R\tlikeCount2\xfd\x03\n" +
	"\fVideoService\x12U\n" +
	"\bGetVideo\x12\x19.video.v1.GetVideoRequest\x1a\x0f.video.v1.Video\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/videos/{bvid}\x12f\n" +
	"\fGetVideoPlay\x12\x1d.video.v1.GetVideoPlayRequest\x1a\x13.video.v1.VideoPlay\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/videos/{bvid}/play\x12f\n" +
	"\fGetVideoLike\x12\x1d.video.v1.GetVideoLikeRequest\x1a\x13.video.v1.VideoLike\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/videos/{bvid}/like\x12`\n" +
	"\tLikeVideo\x12\x1a.video.v1.LikeVideoRequest\x1a\x13.video.v1.VideoLike\"\"\x82\xd3\xe4\x93\x02\x1c\"\x1a/api/v1/videos/{bvid}/like\x12d\n" +
	"\vUnlikeVideo\x12\x1c.video.v1.UnlikeVideoRequest\x1a\x13.video.v1.VideoLike\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v1/videos/{bvid}/likeB7\n" +
	"\bvideo.v1B\n" +
	"VideoProtoP\x01Z\x1dbilibili-lite/api/video/v1;v1b\x06proto3"

var (
	file_video_v1_video_proto_rawDescOnce sync.Once
	file_video_v1_video_proto_rawDescData []byte
)

func file_video_v1_video_proto_rawDescGZIP() []byte {
	file_video_v1_video_proto_rawDescOnce.Do(func() {
		file_video_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_video_v1_video_proto_rawDesc), len(file_video_v1_video_proto_rawDesc)))
	})
	return file_video_v1_video_proto_rawDescData
}

var file_video_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_video_v1_video_proto_goTypes = []any{
	(*Video)(nil),                 // 0: video.v1.Video
	(*VideoPlay)(nil),             // 1: video.v1.VideoPlay
	(*VideoStream)(nil),           // 2: video.v1.VideoStream
	(*DanmakuConfig)(nil),         // 3: video.v1.DanmakuConfig
	(*DanmakuItem)(nil),           // 4: video.v1.DanmakuItem
	(*GetVideoRequest)(nil),       // 5: video.v1.GetVideoRequest
	(*GetVideoPlayRequest)(nil),   // 6: video.v1.GetVideoPlayRequest
	(*GetVideoLikeRequest)(nil),   // 7: video.v1.GetVideoLikeRequest
	(*LikeVideoRequest)(nil),      // 8: video.v1.LikeVideoRequest
	(*UnlikeVideoRequest)(nil),    // 9: video.v1.UnlikeVideoRequest
	(*VideoLike)(nil),             // 10: video.v1.VideoLike
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_video_v1_video_proto_depIdxs = []int32{
	11, // 0: video.v1.Video.publish_time:type_name -> google.protobuf.Timestamp
	2,  // 1: video.v1.VideoPlay.streams:type_name -> video.v1.VideoStream
	3,  // 2: video.v1.VideoPlay.danmaku:type_name -> video.v1.DanmakuConfig
	4,  // 3: video.v1.DanmakuConfig.items:type_name -> video.v1.DanmakuItem
	5,  // 4: video.v1.VideoService.GetVideo:input_type -> video.v1.GetVideoRequest
	6,  // 5: video.v1.VideoService.GetVideoPlay:input_type -> video.v1.GetVideoPlayRequest
	7,  // 6: video.v1.VideoService.GetVideoLike:input_type -> video.v1.GetVideoLikeRequest
	8,  // 7: video.v1.VideoService.LikeVideo:input_type -> video.v1.LikeVideoRequest
	9,  // 8: video.v1.VideoService.UnlikeVideo:input_type -> video.v1.UnlikeVideoRequest
	0,  // 9: video.v1.VideoService.GetVideo:output_type -> video.v1.Video
	1,  // 10: video.v1.VideoService.GetVideoPlay:output_type -> video.v1.VideoPlay
	10, // 11: video.v1.VideoService.GetVideoLike:output_type -> video.v1.VideoLike
	10, // 12: video.v1.VideoService.LikeVideo:output_type -> video.v1.VideoLike
	10, // 13: video.v1.VideoService.UnlikeVideo:output_type -> video.v1.VideoLike
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_video_v1_video_proto_init() }
func file_video_v1_video_proto_init() {
	if File_video_v1_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_video_v1_video_proto_rawDesc), len(file_video_v1_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_video_v1_video_proto_goTypes,
		DependencyIndexes: file_video_v1_video_proto_depIdxs,
		MessageInfos:      file_video_v1_video_proto_msgTypes,
	}.Build()
	File_video_v1_video_proto = out.File
	file_video_v1_video_proto_goTypes = nil
	file_video_v1_video_proto_depIdxs = nil
}
