// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: video/v1/video.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoService_ListVideos_FullMethodName           = "/video.v1.VideoService/ListVideos"
	VideoService_ListUserVideos_FullMethodName       = "/video.v1.VideoService/ListUserVideos"
	VideoService_GetVideo_FullMethodName             = "/video.v1.VideoService/GetVideo"
	VideoService_GetVideoPlay_FullMethodName         = "/video.v1.VideoService/GetVideoPlay"
	VideoService_GetVideoLike_FullMethodName         = "/video.v1.VideoService/GetVideoLike"
	VideoService_LikeVideo_FullMethodName            = "/video.v1.VideoService/LikeVideo"
	VideoService_UnlikeVideo_FullMethodName          = "/video.v1.VideoService/UnlikeVideo"
	VideoService_GetVideoEngagement_FullMethodName   = "/video.v1.VideoService/GetVideoEngagement"
	VideoService_FavoriteVideo_FullMethodName        = "/video.v1.VideoService/FavoriteVideo"
	VideoService_UnfavoriteVideo_FullMethodName      = "/video.v1.VideoService/UnfavoriteVideo"
	VideoService_CoinVideo_FullMethodName            = "/video.v1.VideoService/CoinVideo"
	VideoService_ShareVideo_FullMethodName           = "/video.v1.VideoService/ShareVideo"
	VideoService_ListMyLikedVideos_FullMethodName    = "/video.v1.VideoService/ListMyLikedVideos"
	VideoService_ListMyFavoriteVideos_FullMethodName = "/video.v1.VideoService/ListMyFavoriteVideos"
	VideoService_ListMyCoinedVideos_FullMethodName   = "/video.v1.VideoService/ListMyCoinedVideos"
	VideoService_CreateDanmaku_FullMethodName        = "/video.v1.VideoService/CreateDanmaku"
	VideoService_DeleteDanmaku_FullMethodName        = "/video.v1.VideoService/DeleteDanmaku"
	VideoService_ListVideoComments_FullMethodName    = "/video.v1.VideoService/ListVideoComments"
	VideoService_CreateVideoComment_FullMethodName   = "/video.v1.VideoService/CreateVideoComment"
	VideoService_DeleteVideoComment_FullMethodName   = "/video.v1.VideoService/DeleteVideoComment"
	VideoService_GetVideoUploadStatus_FullMethodName = "/video.v1.VideoService/GetVideoUploadStatus"
	VideoService_PublishVideo_FullMethodName         = "/video.v1.VideoService/PublishVideo"
	VideoService_DeleteVideo_FullMethodName          = "/video.v1.VideoService/DeleteVideo"
	VideoService_StartVideoView_FullMethodName       = "/video.v1.VideoService/StartVideoView"
	VideoService_CompleteVideoView_FullMethodName    = "/video.v1.VideoService/CompleteVideoView"
)

// VideoServiceClient is the client API for VideoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoServiceClient interface {
	ListVideos(ctx context.Context, in *ListVideosRequest, opts ...grpc.CallOption) (*ListVideosReply, error)
	ListUserVideos(ctx context.Context, in *ListUserVideosRequest, opts ...grpc.CallOption) (*ListVideosReply, error)
	GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*Video, error)
	GetVideoPlay(ctx context.Context, in *GetVideoPlayRequest, opts ...grpc.CallOption) (*VideoPlay, error)
	GetVideoLike(ctx context.Context, in *GetVideoLikeRequest, opts ...grpc.CallOption) (*VideoLike, error)
	LikeVideo(ctx context.Context, in *LikeVideoRequest, opts ...grpc.CallOption) (*VideoLike, error)
	UnlikeVideo(ctx context.Context, in *UnlikeVideoRequest, opts ...grpc.CallOption) (*VideoLike, error)
	GetVideoEngagement(ctx context.Context, in *GetVideoEngagementRequest, opts ...grpc.CallOption) (*VideoEngagement, error)
	FavoriteVideo(ctx context.Context, in *FavoriteVideoRequest, opts ...grpc.CallOption) (*VideoEngagement, error)
	UnfavoriteVideo(ctx context.Context, in *UnfavoriteVideoRequest, opts ...grpc.CallOption) (*VideoEngagement, error)
	CoinVideo(ctx context.Context, in *CoinVideoRequest, opts ...grpc.CallOption) (*VideoEngagement, error)
	ShareVideo(ctx context.Context, in *ShareVideoRequest, opts ...grpc.CallOption) (*VideoShare, error)
	ListMyLikedVideos(ctx context.Context, in *ListVideoHistoryRequest, opts ...grpc.CallOption) (*ListVideoHistoryReply, error)
	ListMyFavoriteVideos(ctx context.Context, in *ListVideoHistoryRequest, opts ...grpc.CallOption) (*ListVideoHistoryReply, error)
	ListMyCoinedVideos(ctx context.Context, in *ListVideoHistoryRequest, opts ...grpc.CallOption) (*ListVideoHistoryReply, error)
	CreateDanmaku(ctx context.Context, in *CreateDanmakuRequest, opts ...grpc.CallOption) (*DanmakuItem, error)
	DeleteDanmaku(ctx context.Context, in *DeleteDanmakuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListVideoComments(ctx context.Context, in *ListVideoCommentsRequest, opts ...grpc.CallOption) (*ListVideoCommentsReply, error)
	CreateVideoComment(ctx context.Context, in *CreateVideoCommentRequest, opts ...grpc.CallOption) (*VideoComment, error)
	DeleteVideoComment(ctx context.Context, in *DeleteVideoCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetVideoUploadStatus(ctx context.Context, in *GetVideoUploadStatusRequest, opts ...grpc.CallOption) (*VideoUploadStatus, error)
	PublishVideo(ctx context.Context, in *PublishVideoRequest, opts ...grpc.CallOption) (*Video, error)
	DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	StartVideoView(ctx context.Context, in *StartVideoViewRequest, opts ...grpc.CallOption) (*VideoViewSession, error)
	CompleteVideoView(ctx context.Context, in *CompleteVideoViewRequest, opts ...grpc.CallOption) (*VideoViewResult, error)
}

type videoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoServiceClient(cc grpc.ClientConnInterface) VideoServiceClient {
	return &videoServiceClient{cc}
}

func (c *videoServiceClient) ListVideos(ctx context.Context, in *ListVideosRequest, opts ...grpc.CallOption) (*ListVideosReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideosReply)
	err := c.cc.Invoke(ctx, VideoService_ListVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListUserVideos(ctx context.Context, in *ListUserVideosRequest, opts ...grpc.CallOption) (*ListVideosReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideosReply)
	err := c.cc.Invoke(ctx, VideoService_ListUserVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*Video, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Video)
	err := c.cc.Invoke(ctx, VideoService_GetVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetVideoPlay(ctx context.Context, in *GetVideoPlayRequest, opts ...grpc.CallOption) (*VideoPlay, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoPlay)
	err := c.cc.Invoke(ctx, VideoService_GetVideoPlay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetVideoLike(ctx context.Context, in *GetVideoLikeRequest, opts ...grpc.CallOption) (*VideoLike, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoLike)
	err := c.cc.Invoke(ctx, VideoService_GetVideoLike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) LikeVideo(ctx context.Context, in *LikeVideoRequest, opts ...grpc.CallOption) (*VideoLike, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoLike)
	err := c.cc.Invoke(ctx, VideoService_LikeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) UnlikeVideo(ctx context.Context, in *UnlikeVideoRequest, opts ...grpc.CallOption) (*VideoLike, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoLike)
	err := c.cc.Invoke(ctx, VideoService_UnlikeVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetVideoEngagement(ctx context.Context, in *GetVideoEngagementRequest, opts ...grpc.CallOption) (*VideoEngagement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoEngagement)
	err := c.cc.Invoke(ctx, VideoService_GetVideoEngagement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) FavoriteVideo(ctx context.Context, in *FavoriteVideoRequest, opts ...grpc.CallOption) (*VideoEngagement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoEngagement)
	err := c.cc.Invoke(ctx, VideoService_FavoriteVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) UnfavoriteVideo(ctx context.Context, in *UnfavoriteVideoRequest, opts ...grpc.CallOption) (*VideoEngagement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoEngagement)
	err := c.cc.Invoke(ctx, VideoService_UnfavoriteVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) CoinVideo(ctx context.Context, in *CoinVideoRequest, opts ...grpc.CallOption) (*VideoEngagement, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoEngagement)
	err := c.cc.Invoke(ctx, VideoService_CoinVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ShareVideo(ctx context.Context, in *ShareVideoRequest, opts ...grpc.CallOption) (*VideoShare, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoShare)
	err := c.cc.Invoke(ctx, VideoService_ShareVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListMyLikedVideos(ctx context.Context, in *ListVideoHistoryRequest, opts ...grpc.CallOption) (*ListVideoHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideoHistoryReply)
	err := c.cc.Invoke(ctx, VideoService_ListMyLikedVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListMyFavoriteVideos(ctx context.Context, in *ListVideoHistoryRequest, opts ...grpc.CallOption) (*ListVideoHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideoHistoryReply)
	err := c.cc.Invoke(ctx, VideoService_ListMyFavoriteVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListMyCoinedVideos(ctx context.Context, in *ListVideoHistoryRequest, opts ...grpc.CallOption) (*ListVideoHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideoHistoryReply)
	err := c.cc.Invoke(ctx, VideoService_ListMyCoinedVideos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) CreateDanmaku(ctx context.Context, in *CreateDanmakuRequest, opts ...grpc.CallOption) (*DanmakuItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DanmakuItem)
	err := c.cc.Invoke(ctx, VideoService_CreateDanmaku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) DeleteDanmaku(ctx context.Context, in *DeleteDanmakuRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VideoService_DeleteDanmaku_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) ListVideoComments(ctx context.Context, in *ListVideoCommentsRequest, opts ...grpc.CallOption) (*ListVideoCommentsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVideoCommentsReply)
	err := c.cc.Invoke(ctx, VideoService_ListVideoComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) CreateVideoComment(ctx context.Context, in *CreateVideoCommentRequest, opts ...grpc.CallOption) (*VideoComment, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoComment)
	err := c.cc.Invoke(ctx, VideoService_CreateVideoComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) DeleteVideoComment(ctx context.Context, in *DeleteVideoCommentRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VideoService_DeleteVideoComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) GetVideoUploadStatus(ctx context.Context, in *GetVideoUploadStatusRequest, opts ...grpc.CallOption) (*VideoUploadStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoUploadStatus)
	err := c.cc.Invoke(ctx, VideoService_GetVideoUploadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) PublishVideo(ctx context.Context, in *PublishVideoRequest, opts ...grpc.CallOption) (*Video, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Video)
	err := c.cc.Invoke(ctx, VideoService_PublishVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) DeleteVideo(ctx context.Context, in *DeleteVideoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VideoService_DeleteVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) StartVideoView(ctx context.Context, in *StartVideoViewRequest, opts ...grpc.CallOption) (*VideoViewSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoViewSession)
	err := c.cc.Invoke(ctx, VideoService_StartVideoView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoServiceClient) CompleteVideoView(ctx context.Context, in *CompleteVideoViewRequest, opts ...grpc.CallOption) (*VideoViewResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VideoViewResult)
	err := c.cc.Invoke(ctx, VideoService_CompleteVideoView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoServiceServer is the server API for VideoService service.
// All implementations must embed UnimplementedVideoServiceServer
// for forward compatibility.
type VideoServiceServer interface {
	ListVideos(context.Context, *ListVideosRequest) (*ListVideosReply, error)
	ListUserVideos(context.Context, *ListUserVideosRequest) (*ListVideosReply, error)
	GetVideo(context.Context, *GetVideoRequest) (*Video, error)
	GetVideoPlay(context.Context, *GetVideoPlayRequest) (*VideoPlay, error)
	GetVideoLike(context.Context, *GetVideoLikeRequest) (*VideoLike, error)
	LikeVideo(context.Context, *LikeVideoRequest) (*VideoLike, error)
	UnlikeVideo(context.Context, *UnlikeVideoRequest) (*VideoLike, error)
	GetVideoEngagement(context.Context, *GetVideoEngagementRequest) (*VideoEngagement, error)
	FavoriteVideo(context.Context, *FavoriteVideoRequest) (*VideoEngagement, error)
	UnfavoriteVideo(context.Context, *UnfavoriteVideoRequest) (*VideoEngagement, error)
	CoinVideo(context.Context, *CoinVideoRequest) (*VideoEngagement, error)
	ShareVideo(context.Context, *ShareVideoRequest) (*VideoShare, error)
	ListMyLikedVideos(context.Context, *ListVideoHistoryRequest) (*ListVideoHistoryReply, error)
	ListMyFavoriteVideos(context.Context, *ListVideoHistoryRequest) (*ListVideoHistoryReply, error)
	ListMyCoinedVideos(context.Context, *ListVideoHistoryRequest) (*ListVideoHistoryReply, error)
	CreateDanmaku(context.Context, *CreateDanmakuRequest) (*DanmakuItem, error)
	DeleteDanmaku(context.Context, *DeleteDanmakuRequest) (*emptypb.Empty, error)
	ListVideoComments(context.Context, *ListVideoCommentsRequest) (*ListVideoCommentsReply, error)
	CreateVideoComment(context.Context, *CreateVideoCommentRequest) (*VideoComment, error)
	DeleteVideoComment(context.Context, *DeleteVideoCommentRequest) (*emptypb.Empty, error)
	GetVideoUploadStatus(context.Context, *GetVideoUploadStatusRequest) (*VideoUploadStatus, error)
	PublishVideo(context.Context, *PublishVideoRequest) (*Video, error)
	DeleteVideo(context.Context, *DeleteVideoRequest) (*emptypb.Empty, error)
	StartVideoView(context.Context, *StartVideoViewRequest) (*VideoViewSession, error)
	CompleteVideoView(context.Context, *CompleteVideoViewRequest) (*VideoViewResult, error)
	mustEmbedUnimplementedVideoServiceServer()
}

// UnimplementedVideoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoServiceServer struct{}

func (UnimplementedVideoServiceServer) ListVideos(context.Context, *ListVideosRequest) (*ListVideosReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVideos not implemented")
}
func (UnimplementedVideoServiceServer) ListUserVideos(context.Context, *ListUserVideosRequest) (*ListVideosReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserVideos not implemented")
}
func (UnimplementedVideoServiceServer) GetVideo(context.Context, *GetVideoRequest) (*Video, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideo not implemented")
}
func (UnimplementedVideoServiceServer) GetVideoPlay(context.Context, *GetVideoPlayRequest) (*VideoPlay, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideoPlay not implemented")
}
func (UnimplementedVideoServiceServer) GetVideoLike(context.Context, *GetVideoLikeRequest) (*VideoLike, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideoLike not implemented")
}
func (UnimplementedVideoServiceServer) LikeVideo(context.Context, *LikeVideoRequest) (*VideoLike, error) {
	return nil, status.Error(codes.Unimplemented, "method LikeVideo not implemented")
}
func (UnimplementedVideoServiceServer) UnlikeVideo(context.Context, *UnlikeVideoRequest) (*VideoLike, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlikeVideo not implemented")
}
func (UnimplementedVideoServiceServer) GetVideoEngagement(context.Context, *GetVideoEngagementRequest) (*VideoEngagement, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideoEngagement not implemented")
}
func (UnimplementedVideoServiceServer) FavoriteVideo(context.Context, *FavoriteVideoRequest) (*VideoEngagement, error) {
	return nil, status.Error(codes.Unimplemented, "method FavoriteVideo not implemented")
}
func (UnimplementedVideoServiceServer) UnfavoriteVideo(context.Context, *UnfavoriteVideoRequest) (*VideoEngagement, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfavoriteVideo not implemented")
}
func (UnimplementedVideoServiceServer) CoinVideo(context.Context, *CoinVideoRequest) (*VideoEngagement, error) {
	return nil, status.Error(codes.Unimplemented, "method CoinVideo not implemented")
}
func (UnimplementedVideoServiceServer) ShareVideo(context.Context, *ShareVideoRequest) (*VideoShare, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareVideo not implemented")
}
func (UnimplementedVideoServiceServer) ListMyLikedVideos(context.Context, *ListVideoHistoryRequest) (*ListVideoHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyLikedVideos not implemented")
}
func (UnimplementedVideoServiceServer) ListMyFavoriteVideos(context.Context, *ListVideoHistoryRequest) (*ListVideoHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyFavoriteVideos not implemented")
}
func (UnimplementedVideoServiceServer) ListMyCoinedVideos(context.Context, *ListVideoHistoryRequest) (*ListVideoHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyCoinedVideos not implemented")
}
func (UnimplementedVideoServiceServer) CreateDanmaku(context.Context, *CreateDanmakuRequest) (*DanmakuItem, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDanmaku not implemented")
}
func (UnimplementedVideoServiceServer) DeleteDanmaku(context.Context, *DeleteDanmakuRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDanmaku not implemented")
}
func (UnimplementedVideoServiceServer) ListVideoComments(context.Context, *ListVideoCommentsRequest) (*ListVideoCommentsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVideoComments not implemented")
}
func (UnimplementedVideoServiceServer) CreateVideoComment(context.Context, *CreateVideoCommentRequest) (*VideoComment, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVideoComment not implemented")
}
func (UnimplementedVideoServiceServer) DeleteVideoComment(context.Context, *DeleteVideoCommentRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVideoComment not implemented")
}
func (UnimplementedVideoServiceServer) GetVideoUploadStatus(context.Context, *GetVideoUploadStatusRequest) (*VideoUploadStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideoUploadStatus not implemented")
}
func (UnimplementedVideoServiceServer) PublishVideo(context.Context, *PublishVideoRequest) (*Video, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishVideo not implemented")
}
func (UnimplementedVideoServiceServer) DeleteVideo(context.Context, *DeleteVideoRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVideo not implemented")
}
func (UnimplementedVideoServiceServer) StartVideoView(context.Context, *StartVideoViewRequest) (*VideoViewSession, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVideoView not implemented")
}
func (UnimplementedVideoServiceServer) CompleteVideoView(context.Context, *CompleteVideoViewRequest) (*VideoViewResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteVideoView not implemented")
}
func (UnimplementedVideoServiceServer) mustEmbedUnimplementedVideoServiceServer() {}
func (UnimplementedVideoServiceServer) testEmbeddedByValue()                      {}

// UnsafeVideoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoServiceServer will
// result in compilation errors.
type UnsafeVideoServiceServer interface {
	mustEmbedUnimplementedVideoServiceServer()
}

func RegisterVideoServiceServer(s grpc.ServiceRegistrar, srv VideoServiceServer) {
	// If the following call panics, it indicates UnimplementedVideoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoService_ServiceDesc, srv)
}

func _VideoService_ListVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListVideos(ctx, req.(*ListVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListUserVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserVideosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListUserVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListUserVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListUserVideos(ctx, req.(*ListUserVideosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetVideo(ctx, req.(*GetVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetVideoPlay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoPlayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetVideoPlay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetVideoPlay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetVideoPlay(ctx, req.(*GetVideoPlayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetVideoLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetVideoLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetVideoLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetVideoLike(ctx, req.(*GetVideoLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_LikeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).LikeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_LikeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).LikeVideo(ctx, req.(*LikeVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_UnlikeVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlikeVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).UnlikeVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_UnlikeVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).UnlikeVideo(ctx, req.(*UnlikeVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetVideoEngagement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoEngagementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetVideoEngagement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetVideoEngagement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetVideoEngagement(ctx, req.(*GetVideoEngagementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_FavoriteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FavoriteVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).FavoriteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_FavoriteVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).FavoriteVideo(ctx, req.(*FavoriteVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_UnfavoriteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfavoriteVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).UnfavoriteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_UnfavoriteVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).UnfavoriteVideo(ctx, req.(*UnfavoriteVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_CoinVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).CoinVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_CoinVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).CoinVideo(ctx, req.(*CoinVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ShareVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ShareVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ShareVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ShareVideo(ctx, req.(*ShareVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListMyLikedVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideoHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListMyLikedVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListMyLikedVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListMyLikedVideos(ctx, req.(*ListVideoHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListMyFavoriteVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideoHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListMyFavoriteVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListMyFavoriteVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListMyFavoriteVideos(ctx, req.(*ListVideoHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListMyCoinedVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideoHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListMyCoinedVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListMyCoinedVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListMyCoinedVideos(ctx, req.(*ListVideoHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_CreateDanmaku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDanmakuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).CreateDanmaku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_CreateDanmaku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).CreateDanmaku(ctx, req.(*CreateDanmakuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_DeleteDanmaku_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDanmakuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).DeleteDanmaku(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_DeleteDanmaku_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).DeleteDanmaku(ctx, req.(*DeleteDanmakuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_ListVideoComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVideoCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).ListVideoComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_ListVideoComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).ListVideoComments(ctx, req.(*ListVideoCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_CreateVideoComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVideoCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).CreateVideoComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_CreateVideoComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).CreateVideoComment(ctx, req.(*CreateVideoCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_DeleteVideoComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVideoCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).DeleteVideoComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_DeleteVideoComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).DeleteVideoComment(ctx, req.(*DeleteVideoCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_GetVideoUploadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoUploadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).GetVideoUploadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_GetVideoUploadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).GetVideoUploadStatus(ctx, req.(*GetVideoUploadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_PublishVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).PublishVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_PublishVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).PublishVideo(ctx, req.(*PublishVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_DeleteVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).DeleteVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_DeleteVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).DeleteVideo(ctx, req.(*DeleteVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_StartVideoView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVideoViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).StartVideoView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_StartVideoView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).StartVideoView(ctx, req.(*StartVideoViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoService_CompleteVideoView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteVideoViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoServiceServer).CompleteVideoView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoService_CompleteVideoView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoServiceServer).CompleteVideoView(ctx, req.(*CompleteVideoViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoService_ServiceDesc is the grpc.ServiceDesc for VideoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.v1.VideoService",
	HandlerType: (*VideoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVideos",
			Handler:    _VideoService_ListVideos_Handler,
		},
		{
			MethodName: "ListUserVideos",
			Handler:    _VideoService_ListUserVideos_Handler,
		},
		{
			MethodName: "GetVideo",
			Handler:    _VideoService_GetVideo_Handler,
		},
		{
			MethodName: "GetVideoPlay",
			Handler:    _VideoService_GetVideoPlay_Handler,
		},
		{
			MethodName: "GetVideoLike",
			Handler:    _VideoService_GetVideoLike_Handler,
		},
		{
			MethodName: "LikeVideo",
			Handler:    _VideoService_LikeVideo_Handler,
		},
		{
			MethodName: "UnlikeVideo",
			Handler:    _VideoService_UnlikeVideo_Handler,
		},
		{
			MethodName: "GetVideoEngagement",
			Handler:    _VideoService_GetVideoEngagement_Handler,
		},
		{
			MethodName: "FavoriteVideo",
			Handler:    _VideoService_FavoriteVideo_Handler,
		},
		{
			MethodName: "UnfavoriteVideo",
			Handler:    _VideoService_UnfavoriteVideo_Handler,
		},
		{
			MethodName: "CoinVideo",
			Handler:    _VideoService_CoinVideo_Handler,
		},
		{
			MethodName: "ShareVideo",
			Handler:    _VideoService_ShareVideo_Handler,
		},
		{
			MethodName: "ListMyLikedVideos",
			Handler:    _VideoService_ListMyLikedVideos_Handler,
		},
		{
			MethodName: "ListMyFavoriteVideos",
			Handler:    _VideoService_ListMyFavoriteVideos_Handler,
		},
		{
			MethodName: "ListMyCoinedVideos",
			Handler:    _VideoService_ListMyCoinedVideos_Handler,
		},
		{
			MethodName: "CreateDanmaku",
			Handler:    _VideoService_CreateDanmaku_Handler,
		},
		{
			MethodName: "DeleteDanmaku",
			Handler:    _VideoService_DeleteDanmaku_Handler,
		},
		{
			MethodName: "ListVideoComments",
			Handler:    _VideoService_ListVideoComments_Handler,
		},
		{
			MethodName: "CreateVideoComment",
			Handler:    _VideoService_CreateVideoComment_Handler,
		},
		{
			MethodName: "DeleteVideoComment",
			Handler:    _VideoService_DeleteVideoComment_Handler,
		},
		{
			MethodName: "GetVideoUploadStatus",
			Handler:    _VideoService_GetVideoUploadStatus_Handler,
		},
		{
			MethodName: "PublishVideo",
			Handler:    _VideoService_PublishVideo_Handler,
		},
		{
			MethodName: "DeleteVideo",
			Handler:    _VideoService_DeleteVideo_Handler,
		},
		{
			MethodName: "StartVideoView",
			Handler:    _VideoService_StartVideoView_Handler,
		},
		{
			MethodName: "CompleteVideoView",
			Handler:    _VideoService_CompleteVideoView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "video/v1/video.proto",
}
